#!/usr/bin/env bats
load setup

# --- joy ai update --check ---

@test "joy ai update --check detects tampered SKILL.md" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    # Tamper a generated file if any tool was configured
    for f in .claude/skills/joy/SKILL.md .qwen/skills/joy/SKILL.md .vibe/skills/joy/SKILL.md; do
        if [ -f "$f" ]; then
            echo "tampered" >> "$f"
            run joy ai update --check
            [ "$status" -eq 2 ]
            [[ "$output" == *"outdated"* ]]
            break
        fi
    done
}

@test "joy ai update --check exits 0 when up to date" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    # Immediately after setup, everything should be up to date
    run joy ai update --check
    # status 0 if tools configured and up to date, or no tools at all
    [ "$status" -eq 0 ]
}

# --- joy ai update ---

@test "joy ai update fixes tampered files" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    for f in .claude/skills/joy/SKILL.md .qwen/skills/joy/SKILL.md .vibe/skills/joy/SKILL.md; do
        if [ -f "$f" ]; then
            echo "tampered" >> "$f"
            run joy ai update
            [ "$status" -eq 0 ]
            [[ "$output" == *"updated"* ]]
            # After update, check should pass
            run joy ai update --check
            [ "$status" -eq 0 ]
            break
        fi
    done
}

# --- joy ai check (deprecated alias) ---

@test "joy ai check shows deprecation warning" {
    joy init --name "Test Project"
    run joy ai check
    [[ "$output" == *"deprecated"* ]] || [[ "$stderr" == *"deprecated"* ]] || [ "$status" -eq 2 ]
}

# --- generated file quality ---

@test "generated SKILL.md starts with YAML frontmatter" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    for f in .claude/skills/joy/SKILL.md .qwen/skills/joy/SKILL.md .vibe/skills/joy/SKILL.md; do
        if [ -f "$f" ]; then
            head -1 "$f" | grep -q "^---"
        fi
    done
}

@test "generated files have no version comment" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    found=0
    for f in .claude/skills/joy/SKILL.md .qwen/skills/joy/SKILL.md .vibe/skills/joy/SKILL.md; do
        if [ -f "$f" ] && grep -q "Generated by Joy" "$f"; then
            found=1
        fi
    done
    [ "$found" -eq 0 ]
}

@test "generated agent files have no version comment" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    found=0
    for dir in .claude/agents .qwen/agents .vibe/agents .github/agents; do
        if [ -d "$dir" ]; then
            for f in "$dir"/*; do
                [ -f "$f" ] || continue
                if grep -q "Generated by Joy" "$f"; then
                    found=1
                fi
            done
        fi
    done
    [ "$found" -eq 0 ]
}

# --- instructions reference new commands ---

@test "instructions reference joy ai update not joy ai check" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    for f in .claude/skills/joy/SKILL.md .qwen/skills/joy/SKILL.md; do
        if [ -f "$f" ]; then
            grep -q "joy ai update --check" "$f"
            ! grep -q "joy ai check" "$f"
        fi
    done
}
