#!/usr/bin/env bats
load setup

# --- joy ai setup ---

@test "joy ai setup creates manifest" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    [ -f ".joy/ai/manifest.yaml" ]
}

# --- joy ai update --check ---

@test "joy ai update --check exits 2 when manifest deleted" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    # Only test if tools were configured
    if [ -f ".joy/ai/manifest.yaml" ]; then
        rm .joy/ai/manifest.yaml
        run joy ai update --check
        [ "$status" -eq 2 ]
    fi
}

@test "joy ai update --check reports stale after version tamper" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    if [ -f ".joy/ai/manifest.yaml" ]; then
        sed -i 's/version: .*/version: "0.0.1"/' .joy/ai/manifest.yaml
        run joy ai update --check
        [ "$status" -eq 2 ]
        [[ "$output" == *"outdated"* ]] || [[ "$output" == *"need update"* ]]
    fi
}

# --- joy ai update ---

@test "joy ai update writes manifest" {
    joy init --name "Test Project"
    # First setup, then update
    joy ai setup </dev/null 2>/dev/null || true
    # Tamper manifest version to force staleness
    if [ -f ".joy/ai/manifest.yaml" ]; then
        sed -i 's/version: .*/version: "0.0.1"/' .joy/ai/manifest.yaml
        run joy ai update
        [ "$status" -eq 0 ]
        # Manifest should be updated with current version
        grep -q "version:" .joy/ai/manifest.yaml
    fi
}

# --- joy ai check (deprecated alias) ---

@test "joy ai check shows deprecation warning" {
    joy init --name "Test Project"
    run joy ai check
    [[ "$output" == *"deprecated"* ]] || [[ "$stderr" == *"deprecated"* ]] || [ "$status" -eq 2 ]
}

# --- joy ai reset ---

@test "joy ai reset clears manifest entries" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    joy ai reset --force
    if [ -f ".joy/ai/manifest.yaml" ]; then
        # Manifest should have no tool entries
        ! grep -q "files:" .joy/ai/manifest.yaml
    fi
}

# --- generated file quality ---

@test "generated SKILL.md starts with YAML frontmatter" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    for f in .claude/skills/joy/SKILL.md .qwen/skills/joy/SKILL.md .vibe/skills/joy/SKILL.md; do
        if [ -f "$f" ]; then
            head -1 "$f" | grep -q "^---"
        fi
    done
}

@test "generated files have no version comment" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    # No file should contain "Generated by Joy"
    found=0
    for f in .claude/skills/joy/SKILL.md .qwen/skills/joy/SKILL.md .vibe/skills/joy/SKILL.md; do
        if [ -f "$f" ] && grep -q "Generated by Joy" "$f"; then
            found=1
        fi
    done
    [ "$found" -eq 0 ]
}

@test "generated agent files have no version comment" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    found=0
    for dir in .claude/agents .qwen/agents .vibe/agents .github/agents; do
        if [ -d "$dir" ]; then
            for f in "$dir"/*; do
                [ -f "$f" ] || continue
                if grep -q "Generated by Joy" "$f"; then
                    found=1
                fi
            done
        fi
    done
    [ "$found" -eq 0 ]
}

# --- instructions reference new commands ---

@test "instructions reference joy ai update not joy ai check" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    for f in .claude/skills/joy/SKILL.md .qwen/skills/joy/SKILL.md; do
        if [ -f "$f" ]; then
            grep -q "joy ai update --check" "$f"
            ! grep -q "joy ai check" "$f"
        fi
    done
}
