#!/usr/bin/env bats
load setup

# --- joy ai update --check ---

@test "joy ai update --check detects tampered SKILL.md" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    # Tamper a generated file if any tool was configured
    for f in .claude/skills/joy/SKILL.md .qwen/skills/joy/SKILL.md .vibe/skills/joy/SKILL.md; do
        if [ -f "$f" ]; then
            echo "tampered" >> "$f"
            run joy ai update --check
            [ "$status" -eq 2 ]
            [[ "$output" == *"outdated"* ]]
            break
        fi
    done
}

@test "joy ai update --check exits 0 when up to date" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    # Immediately after setup, everything should be up to date
    run joy ai update --check
    # status 0 if tools configured and up to date, or no tools at all
    [ "$status" -eq 0 ]
}

# --- joy ai update ---

@test "joy ai update fixes tampered files" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    for f in .claude/skills/joy/SKILL.md .qwen/skills/joy/SKILL.md .vibe/skills/joy/SKILL.md; do
        if [ -f "$f" ]; then
            echo "tampered" >> "$f"
            run joy ai update
            [ "$status" -eq 0 ]
            [[ "$output" == *"updated"* ]]
            # After update, check should pass
            run joy ai update --check
            [ "$status" -eq 0 ]
            break
        fi
    done
}

# --- joy ai check (deprecated alias) ---

@test "joy ai check shows deprecation warning" {
    joy init --name "Test Project"
    run joy ai check
    [[ "$output" == *"deprecated"* ]] || [[ "$stderr" == *"deprecated"* ]] || [ "$status" -eq 2 ]
}

# --- generated file quality ---

@test "generated SKILL.md starts with YAML frontmatter" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    for f in .claude/skills/joy/SKILL.md .qwen/skills/joy/SKILL.md .vibe/skills/joy/SKILL.md; do
        if [ -f "$f" ]; then
            head -1 "$f" | grep -q "^---"
        fi
    done
}

@test "generated files have no version comment" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    found=0
    for f in .claude/skills/joy/SKILL.md .qwen/skills/joy/SKILL.md .vibe/skills/joy/SKILL.md; do
        if [ -f "$f" ] && grep -q "Generated by Joy" "$f"; then
            found=1
        fi
    done
    [ "$found" -eq 0 ]
}

@test "generated agent files have no version comment" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    found=0
    for dir in .claude/agents .qwen/agents .vibe/agents .github/agents; do
        if [ -d "$dir" ]; then
            for f in "$dir"/*; do
                [ -f "$f" ] || continue
                if grep -q "Generated by Joy" "$f"; then
                    found=1
                fi
            done
        fi
    done
    [ "$found" -eq 0 ]
}

# --- instructions reference new commands ---

@test "instructions reference joy ai update not joy ai check" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    for f in .claude/skills/joy/SKILL.md .qwen/skills/joy/SKILL.md; do
        if [ -f "$f" ]; then
            grep -q "joy ai update --check" "$f"
            ! grep -q "joy ai check" "$f"
        fi
    done
}

# --- line count enforcement (ADR-026) ---

@test "generated instruction files under 200 lines" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    for f in .claude/CLAUDE.md .qwen/QWEN.md; do
        if [ -f "$f" ]; then
            lines=$(wc -l < "$f")
            [ "$lines" -le 200 ]
        fi
    done
}

@test "generated skill files under 200 lines" {
    joy init --name "Test Project"
    joy ai setup </dev/null 2>/dev/null || true
    for f in .claude/skills/joy/SKILL.md .qwen/skills/joy/SKILL.md .vibe/skills/joy/SKILL.md; do
        if [ -f "$f" ]; then
            lines=$(wc -l < "$f")
            [ "$lines" -le 200 ]
        fi
    done
}

# --- JOY_SESSION in tool settings ---

@test "joy ai setup writes JOY_SESSION to tool settings" {
    setup_human_auth
    joy ai setup </dev/null 2>/dev/null || true
    # Check Claude settings
    if [ -f ".claude/settings.json" ]; then
        grep -q "JOY_SESSION" .claude/settings.json
    fi
    # Check Qwen settings
    if [ -f ".qwen/settings.json" ]; then
        grep -q "JOY_SESSION" .qwen/settings.json
    fi
    # Check Vibe .env
    if [ -f ".vibe/.env" ]; then
        grep -q "JOY_SESSION" .vibe/.env
    fi
    # Check Copilot settings
    if [ -f ".github/copilot/settings.json" ]; then
        grep -q "JOY_SESSION" .github/copilot/settings.json
    fi
}

@test "AI auth works in isolated subshell (simulates AI tool)" {
    setup_human_auth
    joy ai setup </dev/null 2>/dev/null || true
    # Find a configured tool's settings with JOY_SESSION
    SID=""
    for f in .claude/settings.json .qwen/settings.json .github/copilot/settings.json; do
        if [ -f "$f" ]; then
            SID=$(grep -o '"JOY_SESSION": *"[^"]*"' "$f" | head -1 | cut -d'"' -f4)
            break
        fi
    done
    if [ -z "$SID" ] && [ -f ".vibe/.env" ]; then
        SID=$(sed -n 's/^JOY_SESSION=//p' .vibe/.env)
    fi
    [ -n "$SID" ] || skip "no AI tool configured"
    # Find the member ID for this tool
    MEMBER=$(joy project 2>/dev/null | grep "ai:" | head -1 | awk '{print $1}')
    [ -n "$MEMBER" ] || skip "no AI member registered"
    # Create token and authenticate (creates session file)
    TOKEN=$(joy auth token add "$MEMBER" --passphrase "$TEST_PASSPHRASE" \
        | sed -n 's/^  \(joy_t_.*\)/\1/p')
    joy auth --token "$TOKEN" >/dev/null 2>&1
    # Run joy in a clean subshell with ONLY JOY_SESSION from settings.
    # This simulates how AI tools work: each command is a fresh process
    # with no inherited shell state, only env vars from tool settings.
    run env -i HOME="$HOME" PATH="$PATH" XDG_STATE_HOME="$XDG_STATE_HOME" \
        GIT_CONFIG_GLOBAL=/dev/null GIT_AUTHOR_NAME="Test" GIT_AUTHOR_EMAIL="test@example.com" \
        GIT_COMMITTER_NAME="Test" GIT_COMMITTER_EMAIL="test@example.com" \
        JOY_SESSION="$SID" joy add task "Isolated subshell test"
    [ "$status" -eq 0 ]
    # Verify it was attributed to the AI member
    grep -q "delegated-by" .joy/logs/*.log
}
