// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three enforceable interaction levels (JI-0166-D8). Declaration order
 * carries the clamp semantics: `Autonomous < Confirmed < Proposing`, where
 * greater means more human oversight. A `max-interaction-level` floor raises
 * the resolved level toward `Proposing`, never lowers it.
 */
export type InteractionLevel = "autonomous" | "confirmed" | "proposing";
