// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Permission mode of an AI tool session (ADR JAPP-0032): how far a turn
 * may act on its own before asking a human.
 *
 * The variant order is the permission lattice — most restrictive first,
 * `Plan < AcceptEdits < Autonomous`. Do not reorder variants.
 *
 * Not to be confused with [`joy_model::InteractionLevel`],
 * the governed axis this mode is DERIVED from (one-way, see
 * [`from_level`]); the level's `Autonomous` variant sorts LOWEST.
 */
export type AgentMode = "plan" | "accept-edits" | "autonomous";
