id: IT-002D
title: joyint.com deployment
type: task
status: new
priority: medium
epic: EP-0006
deps:
- IT-001D
- IT-0028
created: '2026-03-10T00:19:05.745467804Z'
updated: '2026-03-10T00:19:05.745467804Z'
description: Deploy joy serve to joyint.com as managed service. CI/CD pipeline. SSL, monitoring, backups.
